services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - MONGO_URI=${MONGO_URI}
      - AZURE_TRANSLATOR_KEY=${AZURE_TRANSLATOR_KEY}
      - AZURE_TRANSLATOR_LOCATION=${AZURE_TRANSLATOR_LOCATION}
    restart: unless-stopped
